# ╔═══════════════════════════════════════════════════════════════════════════════════════════╗
# ║  ██████╗ ███╗   ███╗██╗   ██╗██╗     ███████╗████████╗ ██████╗  █████╗ ████████╗███████╗  ║
# ║  ██╔══██╗████╗ ████║██║   ██║██║     ██╔════╝╚══██╔══╝██╔════╝ ██╔══██╗╚══██╔══╝██╔════╝  ║
# ║  ███████║██╔████╔██║██║   ██║██║     █████╗     ██║   ██║  ███╗███████║   ██║   █████╗    ║
# ║  ██╔══██║██║╚██╔╝██║██║   ██║██║     ██╔══╝     ██║   ██║   ██║██╔══██║   ██║   ██╔══╝    ║
# ║  ██║  ██║██║ ╚═╝ ██║╚██████╔╝███████╗███████╗   ██║   ╚██████╔╝██║  ██║   ██║   ███████╗  ║
# ║  ╚═╝  ╚═╝╚═╝     ╚══ ╚═════╝ ╚══════╝╚══════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚══════╝  ║
# ╚═══════════════════════════════════════════════════════════════════════════════════════════╝
#
#
# Plugin made by Vupilex
# My discord contact if you want an update : vupilex
#
#
#   ╔═════════════════════╗
#   ║                     ║
#   ║    CONFIGURATION    ║
#   ║                     ║
#   ╚═════════════════════╝
#
Enable-teleportation-animation: true
#The delay will apply if the teleportation animation is disabled. Delay in seconds
Player-teleportation-delay: 3
Enable-the-teleportation-between-players: true
#Any hologram created before the parameter change will not update. To refresh it, modify the waystone title.
Enable-hologram-title: true
XP-level-teleportation-waystone-cost: 3
#The xp is removed when player send request
XP-level-teleportation-between-players-cost: 3
#Translation available English and French (EN | FR)
lang: "EN"